apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-crud
spec:
  replicas: 2  # Nombre de réplicas
  selector:
    matchLabels:
      app: flask-crud
  template:
    metadata:
      labels:
        app: flask-crud
    spec:
      containers:
      - name: flask-crud
        image: khansaa280/flask-crud:latest  # Image sur Docker Hub
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"