name: CI/CD Pipeline

on:
  push:
    branches:
      - master # Déclencher le pipeline lors d'un push sur la branche main
  pull_request:
    branches:
      - master  # Déclencher le pipeline lors d'une pull request sur la branche main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t khansaa280/flask-crud:latest .

      - name: Run tests
        run: |
          docker run khansaa280/flask-crud:latest python -m pytest

      - name: Push Docker image
        run: docker push khansaa280/flask-crud:latest

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure Kubernetes cluster
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml