name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t khansaa280/flask-crud:latest .

      - name: Push Docker image
        run: docker push khansaa280/flask-crud:latest

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get GitHub Actions Public IP
        id: get_ip
        run: echo "IP=$(curl -s ifconfig.me)" >> $GITHUB_ENV

      - name: Open port 6443 on master node
        run: |
          ssh -o StrictHostKeyChecking=no adminuser@74.176.51.1 << EOF
            sudo ufw allow from $IP to any port 6443 proto tcp
            sudo ufw reload
          EOF
        env:
          IP: ${{ env.IP }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure Kubernetes cluster
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml

      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=$(pwd)/kubeconfig.yaml
          kubectl apply -f k8s/deployment.yaml --validate=false
          kubectl apply -f k8s/service.yaml
          kubectl get pods -o wide

      - name: Close port 6443 on master node
        if: always()
        run: |
          ssh -o StrictHostKeyChecking=no adminuser@74.176.51.1 << EOF
            sudo ufw delete allow from $IP to any port 6443 proto tcp
            sudo ufw reload
          EOF
        env:
          IP: ${{ env.IP }}
