name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change en "main" si besoin
  pull_request:
    branches:
      - master  # Change en "main" si besoin

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t khansaa280/flask-crud:${{ github.sha }} .

      - name: Push Docker image
        run: docker push khansaa280/flask-crud:${{ github.sha }}

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure Kubernetes cluster
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml

      - name: Validate Kubernetes manifests
        run: kubectl apply --dry-run=client -f k8s/deployment.yaml

      - name: Deploy to Kubernetes
        run: |
          export KUBECONFIG=$(pwd)/kubeconfig.yaml
          kubectl set image deployment flask-crud flask-crud=khansaa280/flask-crud:${{ github.sha }}
          kubectl apply -f k8s/service.yaml

      - name: Check Deployment status
        run: kubectl rollout status deployment flask-crud

      - name: Show running pods
        run: kubectl get pods -o wide
